### ISSUE TITLE
Make a release 

### ISSUE THREAD

**Issue by VoidScute** [VectStudio/LED_CUBE#12]
Everything in the title

**Comment by itsharryle** [comment]
@HumanG33k I'm not entire sure why you want a release? You need all the source files, including the .ino file to upload the code to the Arduino.

**Comment by VoidScute** [comment]
Release make easy code change notification (through watch release) and let know to people who want to use your code it’s more than just a test or something like that. 
The notification for release only allow us to add Continuous Delivery.

It s a good practice. And people not always follow the github way of using git (master = stable, this way is bad in my own opinion by the way). People can grab a zip/tar from release page and be sure code will work. Dev test more before doing a release.

**Comment by VoidScute** [comment]
Thx for your job and your release ;)
