### ISSUE TITLE
easyeda

### ISSUE THREAD

**Issue by flags8192** [VectStudio/LED_CUBE#2]
Please give a link to the project in easyeda.

**Comment by krunalnayi** [comment]
Not getting.
Can you please elaborate more?

Thanks,

     KUN@L N@Y!
(Computer Engineer)

Direct: +91-9898-444-899
URL: www.kunalnayi.com
Skype: kunalnayi.1993ee

**Comment by BALILLAZUL01** [comment]
por favor puedes pones como vas contruyendo las capas de los leds yt donde va conectados , el video es muy rápido y no se aprecia 
gracias
