### ISSUE TITLE
Installation Regards

### ISSUE THREAD

**Issue by PARTHKALARIYA** [VectStudio/LED_CUBE#9]
Which Type Of Switch Is Using?
How to install Arduino Code In Arduino Uno R3?

**Comment by parasm0802** [comment]
I used NO switch

**Comment by parasm0802** [comment]
I install Arduino Code In Arduino Uno R3 by laptop

**Comment by itsharryle** [comment]
The original designed did not have any switch. Adding one is not a difficult task though. The Arduino can utilize a button or switch to turn the animations on/off. Cutting the power with a switch is also an option.
